name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull in infracloud.io posts
        uses: gautamkrishnar/blog-post-workflow@v1
        id: blog-post-workflow
        with:
          max_post_count: 2
          feed_list: "https://www.infracloud.io/feed.xml"
          custom_tags: "author/author/name,published/published,image/image/image,summary/summary/summary"
          template: |
            <tr>
              <td>
                <a href="$url">
                  <img width="250px" src="$image">
                </a>
              </td>
              <td>
                <a href="$url">$title</a> <br/>
                by $author
                <br/>
                <br/>
                <p> $summary </p>
              </td>
            </tr>
            $newline